export const endpoints = {
    login: "/v1/auth/login",
    refreshToken: "/v1/auth/refresh-token",
    logout: "/v1/auth/logout",
    requestPasswordReset: "/v1/password/forgot/request/merchant",
    resetPassword: "/v1/password/reset/merchant",
    verifyPasswordResetToken: "/v1/verify/merchant/reset-password-token",
    changePassword: "/v1/change/password/merchant",
    googleMerchantLoginInitiate: "/v1/auth/social/google/merchant/initiate",
    userProfile: "/v1/admin/auth/profile",
    productTemplates: {
        list: "/v2/product-templates",
        byCategory: "/v2/product-templates/by-category/:categoryId",
        detail: "/v2/product-templates/:id",
        create: "/v2/product-templates",
        update: "/v2/product-templates/:id",
        delete: "/v2/product-templates/:id",
    },

    admin: {
        dashboard: {
            overview: "/v1/admin/dashboard/overview",
            merchantTrend: "/v1/admin/dashboard/merchants/trend",
            complianceSummary: "/v1/admin/dashboard/compliance/summary",
        },
        merchants: {
            list: "/v1/admin/merchants",
            complianceQueue: "/v1/admin/merchants/compliance-queue",
            detail: "/v1/admin/merchants/:tenantId",
            updateStatus: "/v1/admin/merchants/:tenantId/status",
            paymentSecrets: "/v1/admin/merchants/:tenantId/payment-secrets",
        },
        compliance: {
            tenantDetail: "/v1/admin/compliance/tenants/:tenantId",
            review: "/v1/admin/compliance/tenants/:tenantId/review",
            filesReview: "/v1/admin/compliance/tenants/:tenantId/files/review",
            rejectionTemplates: "/v1/admin/compliance/rejection-templates",
            override: "/v1/admin/compliance/tenants/:tenantId/override",
        },
        users: {
            list: "/v1/admin/users",
            detail: "/v1/admin/users/:userId",
            updateStatus: "/v1/admin/users/:userId/status",
        },
        settings: {
            list: "/v1/admin/settings",
            upsert: "/v1/admin/settings",
            updateValue: "/v1/admin/settings/:key/value",
            delete: "/v1/admin/settings/:key",
        },
        cache: {
            list: "/v1/admin/cache",
            clearAll: "/v1/admin/cache",
            clearByName: "/v1/admin/cache/:cacheName",
            clearTenant: "/v1/admin/cache/tenant/:tenantId",
        },
        logistics: {
            shipments: "/v1/admin/logistics/shipments",
            usage: "/v1/admin/logistics/shipments/usage",
            waybillFailures: "/v1/admin/logistics/shipments/waybill-failures",
            weightAdjustments: "/v1/admin/logistics/weight-adjustments",
            resolveAdjustment: "/v1/admin/logistics/weight-adjustments/:adjustmentId/resolve",
            providerCapabilities: "/v1/admin/logistics/providers/capabilities",
            providerCapability: "/v1/admin/logistics/providers/capabilities/:provider",
        },
        featureFlags: {
            list: "/v1/admin/feature-flags",
            detail: "/v1/admin/feature-flags/:code",
            create: "/v1/admin/feature-flags",
            update: "/v1/admin/feature-flags/:code",
            tenantOverride: "/v1/admin/feature-flags/:code/tenant-overrides",
        },
        categories: {
            list: "/v1/admin/categories",
            create: "/v1/admin/categories",
            update: "/v1/admin/categories/:id",
            delete: "/v1/admin/categories/:id",
            review: "/v1/admin/categories/custom-review",
            promote: "/v1/admin/categories/custom-review/:id/promote",
        },
        billing: {
            plans: {
                list: "/v1/admin/billing/plans",
                create: "/v1/admin/billing/plans",
                update: "/v1/admin/billing/plans/:id",
                archive: "/v1/admin/billing/plans/:id/archive",
                prices: "/v1/admin/billing/plans/:id/prices",
                updatePrice: "/v1/admin/billing/plan-prices/:priceId",
            },
            subscriptions: {
                list: "/v1/admin/billing/subscriptions",
                tenantSnapshot: "/v1/admin/billing/subscriptions/tenants/:tenantId",
                tenantAuditLogs: "/v1/admin/billing/subscriptions/tenants/:tenantId/audit-logs",
            },
            overrides: {
                apply: "/v1/admin/billing/overrides",
                revoke: "/v1/admin/billing/overrides/:overrideId/revoke",
            },
            extensionCodes: {
                generate: "/v1/admin/billing/extension-codes",
                apply: "/v1/admin/billing/extension-codes/apply",
            },
            extensions: {
                direct: "/v1/admin/billing/extensions/direct",
            },
            invoices: {
                tenant: "/v1/admin/billing/tenants/:tenantId/invoices",
                confirm: "/v1/admin/billing/invoices/:invoiceId/confirm",
            },
        },
    },
}
